apiVersion: v1
kind: Service
metadata:
  name: veru-app-np-service


spec:
  type: NodePort
  selector:
    app: information-technology
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31234