apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: veru-ebs-mysql-pv-claim

spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: veru-ebs-sc
  resources:
    requests:
      storage: 4Gi